id: P1F4A5580
initial_creation_type: ocr
source_metadata:
  volumes:
    85efb0ffee9144028836854982ecbc5b:
      base_file: v105.txt
      image_group_id: I1PD95950
      title: རིགས་པའི་ཐིགས་པའི་ཕྱོགས་སྔ་མ་མདོར་བསྡུས་པ།
      total_pages: 910
      volume_number: 105
